//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuyenDeLoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTiepPhieuNhaps = new HashSet<ChiTiepPhieuNhap>();
        }
    
        public int Ma { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public int MaPhanLoai { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> ChieuCao { get; set; }
        public Nullable<int> ChieuRong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiepPhieuNhap> ChiTiepPhieuNhaps { get; set; }
        public virtual PhanLoai PhanLoai { get; set; }
    }
}
